version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mot de passe root
      MYSQL_DATABASE: stationSki
    volumes:
      - mysql_data:/var/lib/mysql

  spring_project:
    build: .
    container_name: spring_project
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root  # Correspond au mot de passe root MySQL
    depends_on:
      - mysql

volumes:
  mysql_data:
